version: 2.1
orbs:
  node: circleci/node@5
  win: circleci/windows@5.0
  gh: circleci/github-cli@2.6
jobs:
  build-windows-installer:
    executor: win/default
    steps:
      - run:
          command: |
            nvm install 18
            nvm use 18
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Electron make
          command: npm run make
      - store_artifacts:
          path: out/make
          destination: windows
  build-mac-installer:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Electron make
          command: npm run make
      - store_artifacts:
          path: out/make
          destination: macos
workflows:
  build-packages:
    jobs:
      - build-windows-installer:
          filters:
            branches:
              only: 
                - main
      - build-mac-installer:
          filters:
            branches:
              only: 
                - main
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
          notes-file: changelog.md
          requires:
            - build-windows-installer
            - build-mac-installer
          tag: 1.0.0
          title: The initial release
          files: 
            - windows/**/*.exe
            - macos/*.dmg
